from google.adk.tools import google_search
from google.adk.agents import LlmAgent




summary_agent = LlmAgent(
    model="gemini-2.0-flash-exp",
    name="summary_agent",
    description="summarizing the sermon generated by the islamic_sermon_generator rag_agent and extract key words from the sermon",
    instruction="You are a helpful assistant that can summarize the sermon generated by the islamic_sermon_generator rag_agent and extract key words from the sermon",
)





